
log:
  file: STDOUT
  level: DEBUG
  max_age: 2160h
  rotate: 24h

http:
  addr: :10025

model:
  enable: false

payment:
  payment_url: http://payment.ashibro.com
  endpoints:
    wechat:
      provider: wechat
      mch_key: awefawef
      mch_secret: awefawef
      