
log:
  file: STDOUT
  level: DEBUG
  max_age: 2160h
  rotate: 24h

http:
  addr: :8080
  tag: /payground

model:
  enable: false

payment:
  payment_url: https://api.ashibro.com/app/v1/payment-wechat
  endpoints:
    wechat:
      provider: wechat
      mch_key: 1595767231
      mch_secret: JFGxc4TRaYKcwiHi96AhBvxWxx9CUhsO
      
mugglepay:
  token: 